# Generated by Django 6.0.7 on 2026-07-12 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('ALERT', 'Alert')], default='OFFLINE', max_length=20)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('telemetry', models.JSONField(blank=True, default=dict)),
                ('alert_thresholds', models.JSONField(blank=True, default=dict)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='iot_device', to='core.asset')),
            ],
        ),
        migrations.CreateModel(
            name='IoTAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('iot_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.iotdevice')),
            ],
        ),
    ]
