# Generated by Django 6.0.7 on 2026-07-12 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_auditcycle_auditor_remove_auditcycle_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='action_type',
            field=models.CharField(default='STATE_CHANGE', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemlog',
            name='target_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='system_logs', to='core.asset'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='system_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
