# Generated by Django 6.0.7 on 2026-07-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_asset_acquisition_date_asset_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='after_state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='before_state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='target_asset_tag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
